### ISSUE TITLE
Android mobile support

### ISSUE THREAD

**Issue by KaMyKaSii** [D4rkC00d3r/xctvplayer#1]
Does the app support mobile devices?  If not, could you add support? I know you might not understand why this is if the Xbox Game Pass app already works decently on mobile, but with me the app doesn't exceed 6Mbps birate and probably the same happens with other people.  I would like to be able to play with the maximum 15Mbps as it is in the browser with a custom user agent simulating a desktop.
I tried your app but it gets stuck on a gray screen.  By switching the phone orientation to landscape and tapping randomly on the screen, I was able to open a white screen with the Xbox logo loading in the center, but it didn't go further.

**Comment by D4rkC00d3r** [comment]
The app is configured to be a Google TV (formally Android TV) and as such it uses the "LEANBACK_LAUNCHER" that is required to be a TV app. This is super simple for me to make a phone version but it would have to be a separate .apk to download. I will make one in the morning and post it here. Stay tuned.

**Comment by D4rkC00d3r** [comment]
Completed there will be a new app in the releases page with a tag of "non_tv_app".

**Comment by D4rkC00d3r** [comment]
Download the non tv app here in the releases

https://github.com/D4rkC00d3r/xctvplayer/releases/tag/1.1.0_non_tv

**Comment by KaMyKaSii** [comment]
> Download the non tv app here in the releases
> 
> https://github.com/D4rkC00d3r/xctvplayer/releases/tag/1.1.0_non_tv

@D4rkC00d3r thanks for this version!
Unfortunately I was only able to get it to work once. When it worked, I could see that the site and games were in english even though I live in Brazil. It's probably a consequence of having [hard coded](https://github.com/D4rkC00d3r/xctvplayer/blob/ffb75d80e46eb4d7b33c0116e225557247761032/app/src/main/java/com/pixeladdict/xctvplayer/MainActivity.kt#L71) the english site's URL. Could you change to `www.xbox.com/play`? This way the Xbox website will decide which language to use based on the user's location.
I also noticed that I still have the same 6Mbps maximum bitrate. I assume you are using webview in your app, would it be possible to [force a specific](https://developer.android.com/reference/android/webkit/WebSettings#setUserAgentString(java.lang.String)) desktop user agent? So the maximum quality will be offered irrespective of the device. I suggest using the latest user agent of Chrome for Windows: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4756.0 Safari/537.36 Edg/98.0.1107.0`.
And about the app not working anymore, for some reason I got stuck in a gray screen, it persists even after clearing the app data, I tried to wait until 10 minutes but with no results. But this is just a page rendering issue, as you can see in the video I connected a bluetooth keyboard and then I was able to navigate between the page links by TAB + ENTER.
https://user-images.githubusercontent.com/17092335/147511558-f3e323e3-636a-41f5-b55f-c31eff5b6fd9.mp4
Can you reproduce this issue on some Android device? If necessary I can generate a logcat to see if there is something useful for solving the problem.

**Comment by kjbaker-uk** [comment]
@KaMyKaSii Thanks for the feedback I will try your suggestions and get back to you. I have never seen the app get stuck on a grey screen?

**Comment by KaMyKaSii** [comment]
@D4rkC00d3r You're welcome!
This gray screen appears right after the white screen at the start. Another thing I noticed is that when I rotate the phone from landscape to portrait, the white screen comes back again, as if the app had restarted. Do you think with the current code the app should rotate correctly?

**Comment by PeteRepeat77** [comment]
If the user agent change is possible implemented then maybe a drop down box to choose might work well.
