### ISSUE TITLE
App askes for cookies to be accepted.

### ISSUE THREAD

**Issue by D4rkC00d3r** [D4rkC00d3r/xctvplayer#3]
After initial install the app asks cookies to be accepted. This can be done manually on a phone or with a mouse on Google TV. Once accepted it does not ask again unless the app is uninstalled.
![cookie](https://user-images.githubusercontent.com/17799879/147482008-1ac5c6d0-f060-4ac3-ac78-151a9f346229.png)

**Comment by D4rkC00d3r** [comment]
I have tried many ways to automatically accept these pragmatically but it is a limitation due to the version of Android we need to target. Google removed the api calls.

    CookieManager.getInstance().setAcceptCookie(true);

This doesn't work from lollipop(API21) and above. 😭

We will have to manually accept this as mentioned in the first comment.

**Comment by sibbl** [comment]
I can simply accept the cookies using the remote control of the Chromecast with Google TV. Seems no big issue 👍
